### ISSUE TITLE
Very slow work with backblaze

### ISSUE THREAD

**Issue by Lisio** [opendedup/sdfs#82]
Ubuntu: 16.04

For absolutely new volume with empty bucket it spend up to 10 seconds for each new empty directory. What can be the problem with it? Network connection is not an issue, I have stable 100Mbit/s.

**Comment by elanou12** [comment]
I have been experiencing the same issue. Files have been transferring at 1 byte per second,

**Comment by richman1000000** [comment]
My questions is:
1) did you installed sdfs INTO backblaze or it is via network?
2) did you enabled backblaze encryption?

**Comment by elanou12** [comment]
mkfs.sdfs --volume-name=blaze4 --volume-capacity=10GB --backblaze-enabled --cloud-access-key= --cloud-secret-key= --cloud-bucket-name= --enable-replication-master --sdfscli-password=admin

I have tested the same settings with AWS and the issue is not present.

**Comment by opendedup** [comment]
I believe this issue has been addressed in SDFS 3.7. What version are you
running?

**Comment by elanou12** [comment]
I'm currently running 3.7. ....I believe the version right after you fixed the sdfscli --list-cloud-volumes bug that was present for backblaze

**Comment by mattstocum** [comment]
I'm seeing this same issue with sdfs-3.7.8 on CentOS 7. BackBlaze is astonishingly slow, and used up 2500 class C transactions in less than an hour.

**Comment by KimTheFirst** [comment]
I'm seeing the same issue on centos 7 with sdfs 3.7.8

B2 seems to use an inordinate number of transactions when operating and it takes ten seconds to touch a file.

There are no errors being produced, nothing in logs to indicate what the issue might be. More than happy to do some more digging if I get the time or someone wants to suggest a good starting place.

**Comment by KimTheFirst** [comment]
For some reason this appears to be somewhat mitigated by using Ubuntu Server 18.04.2 LTS. Anyone who can't be arsed troubleshooting this on Centos, I advise you to try Ubuntu first before smashing up the server.

The issue is still present and it is still considerably slower than Azure, but the single file read / write time is significantly improved. I guess that interactions with some filesystem related package might be contributing to the issue.

**Comment by KimTheFirst** [comment]
![image](https://user-images.githubusercontent.com/15432758/55009836-19c0ab00-4fdb-11e9-9f20-80104ec6f6ed.png)

I decided to run a veeam backup at the dedup server to generate some load. There seems to be a ridiculously large number of transactions being generated, but "b2_list_file_names" seems to be the worst.
